apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 091020206356.dkr.ecr.us-east-1.amazonaws.com/frontend:18f547300f1790c650f6fca53db5ec03b8c5c4c0
          ports:
            - containerPort: 3000
